/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package perpusapp.form;

import javax.swing.*;
import net.miginfocom.swing.MigLayout;
import com.formdev.flatlaf.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.ResultSet;
import java.sql.Statement;
import perpusapp.PerpusApp;

/**
 *
 * @author Fathi
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        init();
    }

    private void init() {
        setLayout(new MigLayout("fill, insets 20", "[center]", "[center]"));
        txtUsername = new JTextField();
        txtPassword = new JPasswordField();
        cmdLogin = new JButton("Login");
        JPanel panel = new JPanel(new MigLayout("wrap,fillx,insets 35 45 40 45", "fill,250:280"));
        panel.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:20;");
        txtPassword.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true");

        txtUsername.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan kode petugas anda");
        txtPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan password anda");
        add(panel);
        JLabel lblTitle = new JLabel("Perpustakaan");
        lblTitle.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +10");
        JLabel desc = new JLabel("Silahkan login dengan akun anda");
        desc.putClientProperty(FlatClientProperties.STYLE, ""
                + "[light]foreground:lighten(@foreground, 30%);"
                + "[dark]foreground:darken(@foreground, 30%);");
        cmdLogin.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;"
                + "arc:10;"
                + "margin:4,6,4,6;"); // Set the minimum width
        txtUsername.setMinimumSize(new Dimension(50, 35));
        txtPassword.setMinimumSize(new Dimension(50, 35));
        cmdLogin.setMinimumSize(new Dimension(50, 40));

        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "[light]background:darken(@background, 5%);");
        panel.add(lblTitle);
        panel.add(desc);
        panel.add(new JLabel("Kode Petugas"), "gapy 8");
        panel.add(txtUsername);
        panel.add(new JLabel("Password"), "gapy 8");
        panel.add(txtPassword);
        panel.add(cmdLogin, "gapy 20");

        cmdLogin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PerpusApp.login(txtUsername.getText(), txtPassword.getPassword());
            }

        }
        );

        txtUsername.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    PerpusApp.login(txtUsername.getText(), txtPassword.getPassword());
                }
            }

        });

        txtPassword.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    PerpusApp.login(txtUsername.getText(), txtPassword.getPassword());
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JButton cmdLogin;

}
